sudo: required
services:
    - docker

before_install:
    - docker build -t bautheac/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bautheac/react-test npm test

after_success:
    - sudo su
    - docker build -t bautheac/multi-client ./client
    - docker build -t bautheac/multi-nginx ./nginx
    - docker build -t bautheac/multi-server ./server
    - docker build -t bautheac/multi-worker ./worker

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
